### ISSUE TITLE
Residence give confirmation

### ISSUE THREAD

**Issue by frendlyZ** [Zrips/Residence#593] opened 2020-11-09 08:53 UTC
Hello,

I have a problem with the /res give command. After issuing the command I get a message to click to give a residence, but when clicking on it, nothing happens. I tried using older versions, but the issue still persists.
I'm not getting any error messages in console or chat.

Thanks for an answer :)

**Comment by Baterka** [comment] 2020-11-14 14:58
Works for me... Send plugins list and exact version + fork

**Comment by Zrips** [comment] 2020-11-17 14:05
@frendlyZ 
Give exact command you used and command you are getting into console when you click on confirmation command

**Comment by frendlyZ** [comment] 2020-11-19 22:54
I used a command /res give <name> <nick>.

Here is what it says https://imgur.com/a/lI5qu2I.
After clicking on the message nothing happens.

**Comment by Zrips** [comment] 2020-11-20 09:38
@frendlyZ 
What about console? You should get a command being performed message which would indicate what it did performed exactly

**Comment by frendlyZ** [comment] 2020-11-23 21:12
https://imgur.com/a/LV9btmE
It just shows the command that was performed, but that's all

**Comment by frendlyZ** [comment] 2020-11-25 21:59
Here is the list of my plugins
https://imgur.com/a/NqtQMcv

Thanks.

**Comment by Zrips** [comment] 2021-02-05 14:41
Well from all the testing it seams to be caused by some 3rd party plugin interfering with clickable messages. In general clicking on that message performs command. Would suggest to perform some general testing at your end by disabling all plugins except Residence to make sure that this originates from Residence and not somewhere else. 
Closing ticket. If issue will be from residence please open new ticket with atleast version of your server

**Closed by Zrips** 2021-02-05 14:41 UTC
Labels: Unconfirmed issue
