### ISSUE TITLE
Res expand and res contract giving internal error in 4.8.4.4

### ISSUE THREAD

**Issue by kaniesha** [Zrips/Residence#263] opened 2019-02-03 21:51 UTC
Error: https://pastebin.com/CtVpbBEC
craftBukkit: 1.13.2-R0.1-SNAPSHOT (15 versions behind)
Residence: 4.8.4.4
Vault: 1.7.1-b91
Permissions: LuckPerms
Current config: https://pastebin.com/0Tq72j9x

Note: I can use res expand and res contract without issue if I disable FAWE https://github.com/boy0001/FastAsyncWorldedit

**Comment by arturek1666** [comment] 2019-04-15 12:34
I have same issue with:
FastAsyncWorldEdit-bukkit-1.13.65
It's because residence don't support newest fawe hope it will be fixed soon.

**Comment by Zrips** [comment] 2019-04-15 13:02
@arturek1666 can you confirm that FAWE 1.13.65 doesn't work for you with Residence4.8.4.4? As i just tested it out and its working as it should.

**Comment by arturek1666** [comment] 2019-04-15 13:05
I got this:
```
[14:42:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v4.8.4.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-620]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-620]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-620]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-620]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-620]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/BlockVector
	at com.bekvon.bukkit.residence.selection.WorldGuardUtil.getRegion(WorldGuardUtil.java:49) ~[?:?]
	at com.bekvon.bukkit.residence.selection.WorldGuardUtil.isSelectionInArea(WorldGuardUtil.java:73) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ClaimedResidence.addArea(ClaimedResidence.java:437) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.addResidence(ResidenceManager.java:234) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidenceManager.addResidence(ResidenceManager.java:188) ~[?:?]
	at com.bekvon.bukkit.residence.commands.create.perform(create.java:34) ~[?:?]
	at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:156) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-620]
	... 15 more
```

**Comment by Zrips** [comment] 2019-04-15 13:15
Ok, confirmed, will be fixed

**Comment by Zrips** [comment] 2019-04-15 13:32
c88a3c6e7d1851c023d7f1b608bb70cc109298c1

**Closed by Zrips** 2019-04-15 13:32 UTC
