### ISSUE TITLE
Expansion NOT work normally in Nether

### ISSUE THREAD

**Issue by MCPrime666** [Zrips/Residence#838] opened 2022-01-16 14:34 UTC
1. After expanding a residence downwards in nether, the original residence will be shifted downwards
2. Residences can only be expanded up to 128 blocks,NOT 255

**Comment by MCPrime666** [comment] 2022-01-16 14:35
PS: the game version is 1.18.1

**Comment by Zrips** [comment] 2022-01-17 14:21
Cant reproduce issue with shifting residence. Are you using /res expand 5 while standing inside residence or something else?
For nether height, you can define its limit in config file under netherHeight section which defaults to 127 and changing to something more appropriate for your use case will have desired effect. In most cases nether ends at 127 Y level, so we are limiting height to this value to avoid claiming of area which cant be used by players.

**Comment by MCPrime666** [comment] 2022-01-17 23:33
> 

yes, I stood inside the residence when I was expanding. I guess admins of the server set the limited height of residence down in nether to 128, but when I created this residence in server,it was not set. When I was expanding, the server've been set to 128 so after expanding, the original residence was moved downward as a whole...

**Comment by Zrips** [comment] 2022-08-11 13:17
Should be resolved with latest builds

**Closed by Zrips** 2022-08-11 13:17 UTC

**Comment by ShoiLyaung** [comment] 2023-01-15 11:59
I met the same issue.
