### ISSUE TITLE
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)

### ISSUE THREAD

**Issue by DexterSK** [Zrips/Residence#841] opened 2022-01-18 23:55 UTC
[00:52:33 WARN]: [Residence] Task #2405 for Residence v5.0.1.1 generated an exception
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)'
        at com.bekvon.bukkit.residence.slimeFun.SlimefunManager.lambda$0(SlimefunManager.java:23) ~[Residence5.0.1.1.jar

**Comment by misuda12** [comment] 2022-02-04 14:38
https://github.com/Zrips/Residence/commit/177366d487f47c10a0ed131a3c4f56c557dbb6d1
It has already been resolved. Just wait for final release

**Comment by misuda12** [comment] 2022-02-04 14:39
Duplicate of #845

**Comment by 100petr** [comment] 2022-02-04 14:44
this is 17 days old, 845 16 days. so the duplicate is 845

**Comment by Zrips** [comment] 2022-02-04 16:05
177366d487f47c10a0ed131a3c4f56c557dbb6d1

**Closed by Zrips** 2022-02-04 16:05 UTC
