### ISSUE TITLE
residence removing enderdragon from end world

### ISSUE THREAD

**Issue by chillerkraft** [Zrips/Residence#54] opened 2017-05-28 02:41 UTC
when i create a residence covering the whole middle end island, the dragon dissapears, i don't know why. i need the dragon there

**Comment by smmmadden** [comment] 2017-05-28 12:07
Hi ChillerKraft, take a look at the [flags](https://github.com/Zrips/Residence/wiki/Flag-Default-Settings-and-Behavior) on the residence.  While residence would allow creating a residence in The_End, I don't believe you really want to do that for this and other reasons.  There are a number of flags which prevent the spawning of hostile mobs and the dragon is definitely one of them. :-)

**Comment by chillerkraft** [comment] 2017-05-28 15:36
i do want to create a residence in the middle of the end.. i want to set up
the flags so that the dragon can spawn... i didnt change any of the default
flags except for pvp. which flags could it be that i need to disable? ill
try natural hostile mobs again but i did notice when i made spawn residence
that hostile mobs flag had to be turned off to stop them from spawning. so
it made me think the dragon would be okay

On May 28, 2017 8:07 AM, "Steve Mekkelsen Madden" <notifications@github.com>
wrote:

Hi ChillerKraft, take a look at the flags
<https://github.com/Zrips/Residence/wiki/Flag-Default-Settings-and-Behavior>
on the residence. While residence would allow creating a residence in
The_End, I don't believe you really want to do that for this and other
reasons. There are a number of flags which prevent the spawning of hostile
mobs and the dragon is definitely one of them. :-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Zrips/Residence/issues/54#issuecomment-304509640>, or mute
the thread

**Comment by smmmadden** [comment] 2017-05-28 17:29
Take a look at all the flags in the wiki page.  If you haven't changed any after installing the plugin, chances are high that's not what you want for default flags in The_End.

**Comment by chillerkraft** [comment] 2017-05-28 18:02
im honestly so confused
i think there's a problem with the plugin
the default flags allow monsters to be and spawn so they shouldnt effect the dragon
can you please tell me what i need to change from default in order to make the dragon not dissapear

**Comment by chillerkraft** [comment] 2017-05-28 18:18
lets take note im doing /res auto to create a residence 1000x1000x1000 in the middle of the end
the dragon dissapears and when i try to respawn it it disspears again. there are endermen spawning.

**Comment by chillerkraft** [comment] 2017-05-28 19:07
i did look at the wiki. its all the flags i already saw in /res set.

**Comment by smmmadden** [comment] 2017-05-28 19:10
You need to take the time to learn the flags on residences.  There is no way around that part.  The flags.yml will show you what is enabled by default and when standing in a residence you can do a /res info to see what flags were setup for the residence in The_End.  I helped document the wiki page quite a bit to provide all the details you need.  I also test the plugin in multiple worlds and everything is working as the developer made.

**Comment by chillerkraft** [comment] 2017-05-28 19:11
i think i've took enough time sir

**Comment by chillerkraft** [comment] 2017-05-28 19:14
i request that you do /res auto in the_end in the middle, to create a 1000x1000x256 area around you, and do this without the dragon being removed, and please tell me the extra steps you took to make this happen. Please..
i believe there's a bug

**Comment by smmmadden** [comment] 2017-05-28 22:12
I think you may be more confused as what I was pointing you to is all the flags, their descriptions and default settings.  You have to look at that and compare to what you have in your flags.yml and what is shown in /res info

Since no one has access to you your flags.yml or your server the option you have is to try out different flags and if then nothing works as expected, that may be by design or a bug.  But I'm not hearing from your replies what you tried or didn't try.  I can't do the work for you unfortunately. :-)

**Comment by chillerkraft** [comment] 2017-05-28 22:18
the only reason im confused is because the dragon is disspearing when the flags set should be allowing it to be there. i do believe this is a bug. i don't need to show my flags.yml since it's default. i also tried setting flags nmonsters true, nomob false, cmonsters true, monsters true and smonsters true through /res set and tried respawning the dragon but it would dissapear right after spawning

**Comment by smmmadden** [comment] 2017-05-29 14:55
okay - one last try.  The dragon's home is in The_End and therefore should not be enclosed in a Residence.  It's his/her home, so there is no reason I can think of to place a residence over the area where the dragon resides unless you're purposely evicting the dragon. :-)  I don't understand why you feel the need to have to do this in the first place, but that's me.  Whether or not this is possible, that'll be up to the developer @Zrips to decide but I would say this is not a good use of the plugin.  You can create residences in The_End, but where the dragon is...my opinion is no.

I've done everything to try to get you to review the flags in the three areas and each time you say your using the defaults - each time I stated you need to review what they are.  A default is just that, it does not mean everything will work as you expect it to if you don't change anything.   This will be my last comment on it as it has already taken too much of my time.  Good luck!

**Comment by chillerkraft** [comment] 2017-05-29 18:06
well i dont want people building or making residences in the end middle so
im using residence to take over that area.
sorry for you misunderstanding me.

On May 29, 2017 10:55 AM, "Steve Mekkelsen Madden" <notifications@github.com>
wrote:

okay - one last try. The dragon's home is in The_End and therefore should
not be enclosed in a Residence. It's his/her home, so there is no reason I
can think of to place a residence over the area where the dragon resides
unless you're purposely evicting the dragon. :-) I don't understand why you
feel the need to have to do this in the first place, but that's me. Whether
or not this is possible, that'll be up to the developer @Zrips
<https://github.com/zrips> to decide but I would say this is not a good use
of the plugin. You can create residences in The_End, but where the dragon
is...my opinion is no.

I've done everything to try to get you to review the flags in the three
areas and each time you say your using the defaults - each time I stated
you need to review what they are. A default is just that, it does not mean
everything will work as you expect it to if you don't change anything. This
will be my last comment on it as it has already taken too much of my time.
Good luck!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Zrips/Residence/issues/54#issuecomment-304680812>, or mute
the thread

**Comment by chillerkraft** [comment] 2017-06-06 06:01
@smmmadden i tried using worldguard to protect the end, would u say thats a better alternative?
but my problem now is i simply cant build in residences when i have worldguard installed on my server
i've made another ticket for that issue and contacted multiple people even worldguard ppl. good luck. thankyou.

**Comment by chillerkraft** [comment] 2017-06-06 16:19
using worldguard dev # 1704
and residence 4.6.3.0
and spigot 1.11.2

**Comment by Zrips** [comment] 2017-06-19 11:30
Will be fixed with next build

**Closed by Zrips** 2017-06-19 11:30 UTC
