### ISSUE TITLE
Residence SlimeFun Error

### ISSUE THREAD

**Issue by PanHaskins** [Zrips/Residence#853] opened 2022-01-29 11:18 UTC
[12:17:11 WARN]: [Residence] Task #216 for Residence v5.0.1.1 generated an exception
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)'
at com.bekvon.bukkit.residence.slimeFun.SlimefunManager.lambda$0(SlimefunManager.java:23) ~[Residence5.0.1.1.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.18.1.jar:git-Purpur-1462]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1462]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[purpur-1.18.1.jar:git-Purpur-1462]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.1.jar:git-Purpur-1462]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.1.jar:git-Purpur-1462]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1462]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1462]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ybw0014** [comment] 2022-01-30 19:24
Duplicate of #845

**Comment by Zrips** [comment] 2022-02-04 14:27
177366d487f47c10a0ed131a3c4f56c557dbb6d1

**Closed by Zrips** 2022-02-04 14:27 UTC
